[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mimalloc = "0.1"
ntex = { version = "1", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
once_cell = { version = "1", features = ["parking_lot"] }

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
